<a href="https://colab.research.google.com/github/miris-mimitako/g-colab/blob/main/test.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import numpy as np


In [5]:
print (np.__version__)
np.show_config()

1.19.5
blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
blas_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
lapack_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]


In [6]:
z = np.zeros(10)
print (z)


[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [7]:
z = np.zeros((10,10))
print ("%d bytes" % (z.size * z.itemsize))

800 bytes


In [8]:
z = np.zeros(10)
z[4] = 1
print (z)


[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [9]:
z = np.arange(10,50)
print (z)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [10]:
 z = z[::-1]
 print (z)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


In [11]:
z = np.arange(50)
z = z[::-1]
print (z)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2
  1  0]


In [12]:
z = np.arange(9).reshape(3,3)
print (z)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [13]:
nz = np.nonzero([1,2,0,0,4,0])
print (nz)

(array([0, 1, 4]),)


In [14]:
z = np.eye(3)
print (z)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [15]:
z = np.random.random((3,3,3))
print (z)

[[[0.33114677 0.08602904 0.32953805]
  [0.58408881 0.70238834 0.1839726 ]
  [0.2257587  0.43737618 0.5989335 ]]

 [[0.65827676 0.82363648 0.86937396]
  [0.48500866 0.50935885 0.40750933]
  [0.50144179 0.16614543 0.48059888]]

 [[0.83766037 0.33613914 0.94323154]
  [0.27514429 0.8797623  0.834375  ]
  [0.60993079 0.27355579 0.90100637]]]


In [16]:
z = np.random.random((10,10))
zmin,zmax = z.min(),z.max()
print (zmin,zmax)

0.008622328459438 0.9990139191836235


In [17]:
z = np.random.random(30)
m  = z.mean()
print (m)

0.5449486750059838


In [18]:
z = np.ones((10,10))
z[1:-1, 1:-1] =0
print (z)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [23]:
z = np.ones((5,5))
z = np.pad (z, pad_width=1, mode='constant', constant_values=0)
print(z)

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


In [30]:
print (0 * np.nan)
print (np.nan == np.nan)
print (np.inf > np.nan)
print (np.nan - np.nan)
print (np.nan in set([np.nan]))
print (0.3 == 3 * 0.1)

nan
False
False
nan
True
False


In [32]:
z = np.diag(1+np.arange(4),k=-1)
print (z)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


In [33]:
print (np.unravel_index(99,(6,7,8)))

(1, 5, 3)


In [35]:
z = np.zeros((8,8),dtype=int)
z[1::2,::2] =1
z[::2,1::2] =1
print (z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [38]:
z = np.tile(np.array([[0,1],[1,0]]),(4,4))
print (z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]
